// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    // shadcn-vue components are generated by the CLI, kept as-is so `add` and
    // upgrades stay clean.
    ignores: ['app/components/ui/**']
  }
)
